on: push

jobs:
  test:
    runs-on: ubuntu-latest

  services:
    db:
      image: postgres:11
      ports: ['5432:5432']
      env:
        POSTGRES_PASSWORD: postgres
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
      - name: Setup Elixir
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.4.1
        with:
          otp-version: '23.0.2'
          elixir-version: '1.10.3'
      - run: mix deps.get
      - run: mix test